//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangSP
    {
        public HangSP()
        {
            this.NhaCungCaps = new HashSet<NhaCungCap>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaHang { get; set; }
        public string TenHang { get; set; }
    
        public virtual ICollection<NhaCungCap> NhaCungCaps { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
