//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int MaKho { get; set; }
        public string TenKho { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaSP { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
